import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import projects from "./../data/projects.json"
import Project from '../components/Project'
import { useEffect } from 'react'
import gsap from 'gsap'
import { ScrollSmoother } from 'gsap/dist/ScrollSmoother'
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger'
import Menu from '../components/Menu/Menu'

const inter = Inter({ subsets: ['latin'] })

gsap.registerPlugin(ScrollSmoother, ScrollTrigger)

export default function Home() {
  const [smoother , setSmoother] = React.useState({})
  useEffect(() => {
    const smoother = ScrollSmoother.create({
      content: "#projectWrapper",
      wrapper:"#site-container",
      smooth:1
  })
  smoother.effects(".projectImage" , {speed:"auto"})

  
  }, [smoother])
  return (
        <div className={styles.container}>
    <Head>
        <title>My Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Menu />
        <div className="site-container" id={"site-container"}>
          <div className={styles.projectsWrapper} id={"projectWrapper"} >
            {
              projects.map((project, i) => (
                  <Project title={project.title} type={project.type} image={project.image} key={i} i={i} slug={project.slug}
                    />

              ))
            }
          </div>
        </div>
      </main>
    </div>
  )
}
