import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import projects from "./../data/projects.json"
import Project from '../components/Project'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="site-container">
          <div className={styles.projectsWrapper} >
            {
              projects.map((project, i) => (
                  <Project title={project.title} type={project.type} image={project.image} key={i} i={i} slug={project.slug}/>

              ))
            }
          </div>
        </div>
      </main>
    </div>
  )
}
